services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  springboot-app:
    build: .
    ports:
      - "8085:8080"
    depends_on:
      - postgres

volumes:
  postgres-data:
